# Generated by Django 4.2.5 on 2023-10-16 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admissionapp', '0004_alter_admissionform_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admissionapp.admissionform')),
            ],
        ),
    ]
