# Generated by Django 4.2.5 on 2023-10-25 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee_structure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='semester_total',
            field=models.DecimalField(decimal_places=2, default=10000, max_digits=10),
            preserve_default=False,
        ),
    ]
