# Generated by Django 4.2.5 on 2023-10-25 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee_structure', '0002_semester_semester_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='registration_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
