# Generated by Django 4.2.5 on 2023-10-09 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admissionapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admissionapp.admissionform')),
            ],
        ),
    ]
