# Generated by Django 4.2.5 on 2023-10-08 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50)),
                ('father_name', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='admission_photos/')),
                ('marks_10th', models.DecimalField(decimal_places=2, max_digits=5)),
                ('marks_12th', models.DecimalField(decimal_places=2, max_digits=5)),
                ('admission_batch', models.CharField(max_length=20)),
                ('school_details_12th', models.TextField()),
                ('school_details_10th', models.TextField()),
                ('address', models.TextField()),
                ('pass_out_year_12th', models.IntegerField()),
                ('pass_out_year_10th', models.IntegerField()),
                ('admission_date', models.DateField()),
                ('caste', models.CharField(max_length=20)),
                ('roll_number_12th', models.CharField(max_length=20)),
                ('roll_number_10th', models.CharField(max_length=20)),
                ('aadhar_number', models.CharField(max_length=12, unique=True)),
                ('mobile_number', models.CharField(max_length=10)),
                ('date_of_birth', models.DateField()),
            ],
        ),
    ]
