# Generated by Django 4.2.5 on 2023-10-13 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissionapp', '0002_admissionform_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionform',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/admission_photos/'),
        ),
    ]
