# Generated by Django 4.2.5 on 2023-10-13 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissionapp', '0003_alter_admissionform_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionform',
            name='photo',
            field=models.ImageField(default=3, upload_to='admission_photos/'),
            preserve_default=False,
        ),
    ]
