# Generated by Django 4.2.5 on 2023-10-24 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissionapp', '0005_admissionform_registration_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionform',
            name='last_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='admissionform',
            name='middle_name',
            field=models.CharField(blank=True, default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='admissionform',
            name='registration_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
