# Generated by Django 4.2.5 on 2023-10-26 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissionapp', '0006_alter_admissionform_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionform',
            name='current_semester',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
