# Generated by Django 4.2.5 on 2023-11-04 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissionapp', '0008_admissionform_dist_admissionform_pin_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionform',
            name='email',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='admissionform',
            name='gender',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='admissionform',
            name='state',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
