# Generated by Django 4.2.5 on 2023-10-25 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fee_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fee',
            old_name='Semester',
            new_name='semester',
        ),
    ]
