# Generated by Django 4.2.5 on 2023-10-25 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee_management', '0002_rename_semester_fee_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='discount_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='fee',
            name='late_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
