# Generated by Django 4.2.5 on 2023-10-26 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee_management', '0005_fee_total_semester_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='comments',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
